import assert from "node:assert/strict";
import { useAutomationDraftStore as store, automationDraftDirty } from "../store/automationDrafts";
import type { HeartbeatTask } from "../custom/features/heartbeat/heartbeat.types";
const task: HeartbeatTask = { id: "a", title: "Original", prompt: "Saved prompt", interval: "30m", enabled: true, createdAt: 1 };
store.setState({ entries: {} });
store.getState().ensure(task);
assert.equal(automationDraftDirty(store.getState().entries.a), false);
store.getState().edit("a", (draft) => ({ ...draft, title: "Local" }));
store.getState().ui("a", { frequency: "cron", tab: "history" });
store.getState().reconcile([{ ...task, prompt: "External", topicId: "run", lastRunAt: 10 }]);
let entry = store.getState().entries.a;
assert.equal(entry.draft.title, "Local");
assert.equal(entry.draft.prompt, "External");
assert.equal(entry.draft.topicId, "run");
assert.equal(entry.frequency, "cron");
assert.equal(entry.tab, "history");
assert.deepEqual(entry.conflicts, []);
// Task 199: model override (provider/model) and goal fields are editable — a
// draft that only changed them must read dirty, or the save button stays
// disabled while the status bar keeps claiming "saved" (the reported bug).
store.getState().discard("a");
assert.equal(automationDraftDirty(store.getState().entries.a), false, "baseline must start clean");
store.getState().edit("a", (draft) => ({ ...draft, provider: "mimo", model: "mimo-v2.6-pro" }));
assert.equal(automationDraftDirty(store.getState().entries.a), true, "provider/model edit must mark dirty");
store.getState().edit("a", (draft) => ({ ...draft, goalMode: true, goalText: "finish it" }));
assert.equal(automationDraftDirty(store.getState().entries.a), true, "goal edit must mark dirty");
// An external provider change syncs into an untouched draft …
store.getState().discard("a");
store.getState().reconcile([{ ...task, provider: "deepseek", model: "v4" }]);
entry = store.getState().entries.a;
assert.equal(entry.draft.provider, "deepseek");
assert.equal(automationDraftDirty(entry), false, "synced external provider is not local dirt");
// … and surfaces as a conflict when both sides changed it differently.
store.getState().edit("a", (draft) => ({ ...draft, provider: "mimo" }));
store.getState().reconcile([{ ...task, provider: "glm", model: "air" }]);
entry = store.getState().entries.a;
assert.ok(entry.conflicts.includes("provider"), "diverging provider edits must conflict");
store.getState().discard("a");
assert.equal(automationDraftDirty(store.getState().entries.a), false, "discard restores the synced baseline");
store.getState().edit("a", (draft) => ({ ...draft, title: "Local" }));
store.getState().ui("a", { frequency: "cron", tab: "history" });
store.getState().reconcile([{ ...task, prompt: "External", topicId: "run", lastRunAt: 10 }]);
entry = store.getState().entries.a;
assert.equal(entry.draft.title, "Local");
store.getState().reconcile([{ ...task, title: "Remote", prompt: "External", topicId: "run" }]);
assert.deepEqual(store.getState().entries.a.conflicts, ["title"]);
store.getState().reconcile([{ ...task, title: "Remote", prompt: "External", topicId: "new-run" }]);
assert.deepEqual(store.getState().entries.a.conflicts, ["title"], "repeated refresh must not erase unresolved conflicts");
store.getState().discard("a");
assert.equal(store.getState().entries.a.draft.title, "Remote");
assert.deepEqual(store.getState().entries.a.conflicts, []);
store.getState().edit("a", (draft) => ({ ...draft, prompt: "Keep this" }));
const version = store.getState().begin("a")!;
assert.equal(store.getState().begin("a"), null);
store.getState().edit("a", (draft) => ({ ...draft, prompt: "Wrong" }));
assert.equal(store.getState().entries.a.draft.prompt, "Keep this");
store.getState().finish("a", version - 1, task);
assert.equal(store.getState().entries.a.busy, true);
store.getState().finish("a", version);
assert.equal(store.getState().entries.a.error, true);
assert.equal(store.getState().entries.a.draft.prompt, "Keep this");
store.getState().reconcile([]);
assert.equal(store.getState().entries.a.missing, true);
assert.equal(store.getState().entries.a.draft.prompt, "Keep this");
store.getState().ensure({ ...task, id: "new", createdAt: undefined }, true);
store.getState().reconcile([]);
assert.equal(store.getState().entries.new.missing, false);
assert.equal(store.getState().entries.new.baseline, null);
store.getState().discard("new");
assert.equal(store.getState().entries.new, undefined);
console.log("PASS automation draft merge, conflict, engine state, locking, stale completion and deletion contracts");
