// Provider connections carry two names, and only one of them is user facing.
//
//  - `name` is the stable routing identity: it is persisted inside every
//    `<provider>/<model>` reference (tab state, session meta, heartbeat tasks),
//    so renaming it would break every existing reference. Nothing here does.
//  - `displayName` is the label the user picked for that connection.
//
// Resolution order (task 198): explicit `displayName` > built-in default label >
// `name`. The middle layer exists because an install that never set a display name
// used to show routing ids (`deepseek-flash`, `minimax-M3`, `opencode-go-<uuid>`)
// right next to model names of the same shape, which reads as "the provider list is
// showing models". The default layer is display-only: it is never written back to
// the config, so no session, tab or task reference changes.
//
// This mirrors the contract the Go side already implements — see
// internal/provider/failure_diagnostic.go (ProviderDisplayLabel keeps the display
// name and falls back to the provider id) and internal/config/render_provider_identity.go
// (renders the same `display_name` key). Frontend surfaces should go through here
// rather than invent a second rule.

// builtInProviderLabels maps the provider names this install ships with — plus the
// vendor families users name their own connections after — to a readable label.
// Keys are lower case because matching ignores case (`minimax-M3`).
const builtInProviderLabels: Record<string, string> = {
  deepseek: "DeepSeek",
  "deepseek-flash": "DeepSeek Flash",
  "deepseek-pro": "DeepSeek Pro",
  mimo: "MiMo",
  "mimo-api": "MiMo API",
  "mimo-flash": "MiMo Flash",
  "mimo-pro": "MiMo Pro",
  "mimo-token-plan": "MiMo Token Plan",
  minimax: "MiniMax",
  "minimax-m3": "MiniMax M3",
  glm: "GLM",
  "glm-cn": "GLM CN",
  "opencode-go": "OpenCode Go",
  "opencode-zen": "OpenCode Zen",
};

// Auto-generated connection ids end in a 32-character hex hash; the hash is noise,
// so keep the readable stem and append a short code instead of hiding the
// connection behind an unreadable id.
const autoGeneratedSuffix = /^(.*?)-([0-9a-f]{32})$/i;

// providerDefaultLabel returns the label to show for a connection whose
// `display_name` is not set. Names it does not know are returned unchanged.
export function providerDefaultLabel(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) return trimmed;
  const known = builtInProviderLabels[trimmed.toLowerCase()];
  if (known) return known;
  const auto = autoGeneratedSuffix.exec(trimmed);
  if (auto) return `${providerDefaultLabel(auto[1])} (${auto[2].slice(0, 4)})`;
  return trimmed;
}

// providerDisplayLabel resolves the label a user-facing surface must show while the
// persisted identity stays `provider.name`.
export function providerDisplayLabel(provider: { name: string; displayName?: string }): string {
  return provider.displayName?.trim() || providerDefaultLabel(provider.name);
}
